/*
Deployment Skript zu Erstellung der Datenbankentabellen
Ansprechpartner: Fabian Meise
*/

create table USERTYPES (
    utid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Type VARCHAR(50),
    TechIsActive bit DEFAULT 1,
    TechIsDeleted bit DEFAULT 0,
    TechIsModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USERTYPES(type) VALUES('Administrator');
INSERT INTO USERTYPES(type) VALUES('Kunde');
INSERT INTO USERTYPES(type) VALUES('Mitarbeiter');

create table SAFETYQUESTION (
    sqid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SafetyQuestion VARCHAR(255),   
    TechIsActive bit DEFAULT 1,
    TechIsDeleted bit DEFAULT 0,
    TechIsModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO SAFETYQUESTION(SafetyQuestion) VALUES('Wie lautet der Vorname ihrer Mutter?');
INSERT INTO SAFETYQUESTION(SafetyQuestion) VALUES('Wie lautet der Name ihres Haustiers?');
INSERT INTO SAFETYQUESTION(SafetyQuestion) VALUES('Wie viele Geschwister haben Sie?');
INSERT INTO SAFETYQUESTION(SafetyQuestion) VALUES('Welches Land möchten Sie auf keinen Fall bereisen?');
INSERT INTO SAFETYQUESTION(SafetyQuestion) VALUES('Welcher Shop ist besser als amazon? ;)');

create table USERDATA (
    udid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    Surname VARCHAR(255),
    Email VARCHAR(255),
    Postal VARCHAR(10),
    Street VARCHAR(255),
    CITY VARCHAR(255),
    Phone VARCHAR(255),
    TechIsActive bit DEFAULT 1,
    TechIsDeleted bit DEFAULT 0,
    TechIsModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP        
    );

create table USERLOGIN (
    ulid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Login VARCHAR(50) UNIQUE,
    Password VARCHAR(50),
    SafetyAnswer VARCHAR(255),
    TechIsActive bit DEFAULT 1,
    TechIsDeleted bit DEFAULT 0,
    TechIsModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP    
);
ALTER TABLE USERLOGIN ADD COLUMN sqid int;
ALTER TABLE USERLOGIN ADD FOREIGN KEY(sqid) REFERENCES SAFETYQUESTION(sqid);
ALTER TABLE USERLOGIN ADD COLUMN utid int;
ALTER TABLE USERLOGIN ADD FOREIGN KEY(utid) REFERENCES USERTYPES(utid);
ALTER TABLE USERLOGIN ADD COLUMN udid int;
ALTER TABLE USERLOGIN ADD FOREIGN KEY(udid) REFERENCES USERDATA(udid);

create table CATEGORIES (
    acid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    categorie VARCHAR(255)
);

INSERT INTO CATEGORIES(categorie) VALUES('Kleidung');
INSERT INTO CATEGORIES(categorie) VALUES('Ski-Equipment');
INSERT INTO CATEGORIES(categorie) VALUES('Outdoor-Ausrüstung');

create table ARTICLE (
    aid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    description text,
    TechIsActive bit DEFAULT 1,
    TechIsDeleted bit DEFAULT 0,
    TechIsModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ARTICLE ADD COLUMN acid int;
ALTER TABLE ARTICLE ADD FOREIGN KEY(acid) REFERENCES CATEGORIES(acid);
ALTER TABLE ARTICLE ADD COLUMN manufacturer VARCHAR(255);
ALTER TABLE ARTICLE ADD COLUMN gender VARCHAR(255);

create table ARTICLEVERSION
(
    avid INT NOT NULL
    AUTO_INCREMENT PRIMARY KEY,
    property VARCHAR
    (255),
    propertyvalue VARCHAR
    (255),
    defaultprice DOUBLE
    (40,3),
    TechIsActive bit DEFAULT 1,
    TechIsDeleted bit DEFAULT 0,
    TechIsModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
    ALTER TABLE ARTICLEVERSION ADD COLUMN aid int;
    ALTER TABLE ARTICLEVERSION ADD FOREIGN KEY(aid) REFERENCES ARTICLE(aid);

create table ARTICLEIMAGE(
    aimgid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    IMAGE MEDIUMBLOB,
    TechIsActive bit DEFAULT 1,
    TechIsDeleted bit DEFAULT 0,
    TechIsModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ARTICLEIMAGE ADD COLUMN avid int;
ALTER TABLE ARTICLEIMAGE ADD FOREIGN KEY(avid) REFERENCES ARTICLEVERSION(avid);

CREATE TABLE ARTICLECOLOR
(
    acolid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    color varchar (255),
    hexcode varchar (7)
);

INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Weiß', '#fff');
INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Schwarz', '#000');
INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Grau', '#777');
INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Blau', '#00f');
INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Rot', '#f00');
INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Gelb', '#ff0');
INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Grün', '#0f0');
INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Braun', '#851');
INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Orange', '#fa0');
INSERT INTO ARTICLECOLOR        (color, hexcode)    VALUES('Violett', '#f0f');

CREATE TABLE ARTICLEVERSION_TO_COLOR
(
    avtcid INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);
ALTER TABLE ARTICLEVERSION_TO_COLOR ADD COLUMN avid int;
ALTER TABLE ARTICLEVERSION_TO_COLOR ADD FOREIGN KEY(avid) REFERENCES ARTICLEVERSION(avid);
ALTER TABLE ARTICLEVERSION_TO_COLOR ADD COLUMN acolid int;
ALTER TABLE ARTICLEVERSION_TO_COLOR ADD FOREIGN KEY(acolid) REFERENCES ARTICLECOLOR(acolid);

CREATE TABLE ARTICLEVERSIONSIZE
(
avsid int NOT NULL,
size varchar(255) DEFAULT NULL,
avid int(11) DEFAULT NULL
);

create table SHOPPINGCART(
    scid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Amount int
);
ALTER TABLE SHOPPINGCART ADD COLUMN avid int;
ALTER TABLE SHOPPINGCART ADD FOREIGN KEY(avid) REFERENCES ARTICLEVERSION(avid);
ALTER TABLE SHOPPINGCART ADD COLUMN ulid int;
ALTER TABLE SHOPPINGCART ADD FOREIGN KEY(ulid) REFERENCES USERLOGIN(ulid);
ALTER TABLE SHOPPINGCART ADD COLUMN size varchar(255);

create table ASSIGNMENT(
    orid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    Surname VARCHAR(255),
    Email VARCHAR(255),
    Postcode VARCHAR(10),
    Street VARCHAR(255),
    StreetNo VARCHAR(255),
    CITY VARCHAR(255)    
);
ALTER TABLE ASSIGNMENT ADD COLUMN ulid int;
ALTER TABLE ASSIGNMENT ADD FOREIGN KEY(ulid) REFERENCES USERLOGIN(ulid);

create table ASSIGNMENTSTATUS(
    osid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Status VARCHAR(255),
    statusday DATETIME
);
ALTER TABLE ASSIGNMENTSTATUS ADD COLUMN orid int;
ALTER TABLE ASSIGNMENTSTATUS ADD FOREIGN KEY(orid) REFERENCES ASSIGNMENT(orid) ON DELETE CASCADE;

create table ASSIGNMENTDETAILS(
    odid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ASSIGNMENTPRICE DOUBLE(40,3),
    amount int
);
ALTER TABLE ASSIGNMENTDETAILS ADD COLUMN orid int;
ALTER TABLE ASSIGNMENTDETAILS ADD FOREIGN KEY(orid) REFERENCES ASSIGNMENT(orid) ON DELETE CASCADE;
ALTER TABLE ASSIGNMENTDETAILS ADD COLUMN avid int;
ALTER TABLE ASSIGNMENTDETAILS ADD FOREIGN KEY(avid) REFERENCES ARTICLEVERSION(avid) ON DELETE CASCADE;
ALTER TABLE ASSIGNMENTDETAILS ADD COLUMN acolid int;
ALTER TABLE ASSIGNMENTDETAILS ADD FOREIGN KEY(acolid) REFERENCES ARTICLECOLOR(acolid) ON DELETE CASCADE;
ALTER TABLE ASSIGNMENTDETAILS ADD COLUMN size varchar(255);

CREATE TABLE STOCK
(
    sid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    amount INT 
);
ALTER TABLE STOCK ADD COLUMN avid int;
ALTER TABLE STOCK ADD FOREIGN KEY(avid) REFERENCES ARTICLEVERSION(avid);
ALTER TABLE STOCK ADD COLUMN size varchar(255);
